'use client';

import { motion } from 'motion/react';

const Gallery = () => {
  const images = [
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751677760/ai-creatives/generated/instagram_post-c633724c-9da1-4977-821b-c1e03711ddb3.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751661989/ai-creatives/generated/facebook_post-facebook_post-63a9dbe8-f46d-46f7-9206-768a2452d7de.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751661347/ai-creatives/generated/instagram_post-5086040d-f108-48e8-9de8-550dff711428.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751678802/ai-creatives/generated/instagram_post-5afd9c82-f689-486b-bde5-552d53a1aca8.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751661994/ai-creatives/generated/website_banner-website_banner-e6abbf4e-fd0a-4e64-9989-9c3f6066b322.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751676832/ai-creatives/generated/website_banner-615e3d4a-4450-49df-b7b0-225dd07dec9b.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751662022/ai-creatives/generated/linkedin_post-linkedin_post-86071728-ceb8-4347-bffb-6becc2202fa2.png',
    'https://res.cloudinary.com/dtr7khiig/image/upload/v1751661986/ai-creatives/generated/instagram_post-instagram_post-f91e3b69-846a-419d-aa0b-8e81d1ed99ec.png'
  ];

  return (
    <section className="py-20 px-6 bg-white">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h3 className="text-2xl md:text-3xl font-semibold mb-3 text-gray-900" style={{fontFamily:'Geist,Inter,sans-serif'}}>
            See what our AI creates
          </h3>
          <p className="text-base text-gray-500 max-w-xl mx-auto" style={{fontFamily:'Inter,Geist,sans-serif'}}>
            Real ad creatives generated by Snap AI for brands across industries
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {images.map((imageUrl, index) => (
            <motion.div 
              initial={{ opacity: 0, filter: "blur(10px)", y: 10 }}
              whileInView={{ opacity: 1, filter: "blur(0px)", y: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.7, ease: 'easeOut', delay: index * 0.1 }}
              key={index} 
              className="group relative overflow-hidden rounded-xl bg-gray-100 aspect-square hover:scale-105 transition-transform duration-150 cursor-pointer ease-out"
              style={{boxShadow:'0 2px 12px 0 rgba(60,60,120,0.06)'}}
            >
              <img 
                src={imageUrl} 
                alt={`AI generated creative ${index + 1}`}
                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-300"></div>
              <div className="absolute bottom-3 left-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <div className="text-white text-xs font-medium bg-black/50 px-2 py-1 rounded-md backdrop-blur-sm">
                  AI Generated
                </div>
              </div>
            </motion.div>
          ))}
        </div>
        <div className="text-center mt-8">
          <p className="text-sm text-gray-400" style={{fontFamily:'Inter,Geist,sans-serif'}}>
            Join the waitlist to create your own AI-powered ads
          </p>
        </div>
      </div>
    </section>
  );
};

export default Gallery;